// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// Rcpp_sortDelta
IntegerVector Rcpp_sortDelta(IntegerVector x);
RcppExport SEXP _hEDA_Rcpp_sortDelta(SEXP xSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< IntegerVector >::type x(xSEXP);
    rcpp_result_gen = Rcpp::wrap(Rcpp_sortDelta(x));
    return rcpp_result_gen;
END_RCPP
}
// aggrStrata_RcppOpen
NumericMatrix aggrStrata_RcppOpen(DataFrame strata, int nvar, IntegerVector vett, int censiti, int dominio);
RcppExport SEXP _hEDA_aggrStrata_RcppOpen(SEXP strataSEXP, SEXP nvarSEXP, SEXP vettSEXP, SEXP censitiSEXP, SEXP dominioSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< DataFrame >::type strata(strataSEXP);
    Rcpp::traits::input_parameter< int >::type nvar(nvarSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type vett(vettSEXP);
    Rcpp::traits::input_parameter< int >::type censiti(censitiSEXP);
    Rcpp::traits::input_parameter< int >::type dominio(dominioSEXP);
    rcpp_result_gen = Rcpp::wrap(aggrStrata_RcppOpen(strata, nvar, vett, censiti, dominio));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_hEDA_Rcpp_sortDelta", (DL_FUNC) &_hEDA_Rcpp_sortDelta, 1},
    {"_hEDA_aggrStrata_RcppOpen", (DL_FUNC) &_hEDA_aggrStrata_RcppOpen, 5},
    {NULL, NULL, 0}
};

RcppExport void R_init_hEDA(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
